site_name: База знаний
nav:
  - Главная: index.md
  - Git:
    - Теория: git.md
    - Справочник команд: commands.md
  - Java:
    - Spring и Spring Boot: spring.md
  - Абаут: about.md

theme:
  name: readthedocs

